.align 4
monster_names:
	fixed_string MON_NAME_LENGTH, "몬스터 0"
	fixed_string MON_NAME_LENGTH, "랄도"
	fixed_string MON_NAME_LENGTH, "버니프"
	fixed_string MON_NAME_LENGTH, "무루프슈"
	fixed_string MON_NAME_LENGTH, "마프데트"
	fixed_string MON_NAME_LENGTH, "슈레드"
	fixed_string MON_NAME_LENGTH, "간다레와"
	fixed_string MON_NAME_LENGTH, "에어로지"
	fixed_string MON_NAME_LENGTH, "가르키마세라"
	fixed_string MON_NAME_LENGTH, "딩고"
	fixed_string MON_NAME_LENGTH, "미헨 팡"
	fixed_string MON_NAME_LENGTH, "가름"
	fixed_string MON_NAME_LENGTH, "스노우 울프"
	fixed_string MON_NAME_LENGTH, "샌드 울프"
	fixed_string MON_NAME_LENGTH, "스콜"
	fixed_string MON_NAME_LENGTH, "밴더스내치"
	fixed_string MON_NAME_LENGTH, "워터 푸딩"
	fixed_string MON_NAME_LENGTH, "선더 푸딩"
	fixed_string MON_NAME_LENGTH, "스노우 푸딩"
	fixed_string MON_NAME_LENGTH, "아이스 푸딩"
	fixed_string MON_NAME_LENGTH, "플레임 푸딩"
	fixed_string MON_NAME_LENGTH, "다크 푸딩"
	fixed_string MON_NAME_LENGTH, "디노닉스"
	fixed_string MON_NAME_LENGTH, "이피리아"
	fixed_string MON_NAME_LENGTH, "랩터"
	fixed_string MON_NAME_LENGTH, "멜뤼진"
	fixed_string MON_NAME_LENGTH, "슈메르케"
	fixed_string MON_NAME_LENGTH, "요위"
	fixed_string MON_NAME_LENGTH, "콘도르"
	fixed_string MON_NAME_LENGTH, "시무르그"
	fixed_string MON_NAME_LENGTH, "알키오네"
	fixed_string MON_NAME_LENGTH, "킬러 비"
	fixed_string MON_NAME_LENGTH, "바이트 버그"
	fixed_string MON_NAME_LENGTH, "와스프"
	fixed_string MON_NAME_LENGTH, "네비로스"
	fixed_string MON_NAME_LENGTH, "플로트 아이"
	fixed_string MON_NAME_LENGTH, "부에르"
	fixed_string MON_NAME_LENGTH, "이블 아이"
	fixed_string MON_NAME_LENGTH, "아리만"
	fixed_string MON_NAME_LENGTH, "발삼"
	fixed_string MON_NAME_LENGTH, "그랫"
	fixed_string MON_NAME_LENGTH, "사하긴"
	fixed_string MON_NAME_LENGTH, "사하긴"
	fixed_string MON_NAME_LENGTH, "사하긴"
	fixed_string MON_NAME_LENGTH, "가루다"
	fixed_string MON_NAME_LENGTH, "즈"
	fixed_string MON_NAME_LENGTH, "샌드 웜"
	fixed_string MON_NAME_LENGTH, "랜드 웜"
	fixed_string MON_NAME_LENGTH, "호법기사"
	fixed_string MON_NAME_LENGTH, "영식 호법기사"
	fixed_string MON_NAME_LENGTH, "고스트"
	fixed_string MON_NAME_LENGTH, "플레기아스"
	fixed_string MON_NAME_LENGTH, "아케오로스"
	fixed_string MON_NAME_LENGTH, "레모라"
	fixed_string MON_NAME_LENGTH, "레이징 스파이크"
	fixed_string MON_NAME_LENGTH, "듀얼 혼"
	fixed_string MON_NAME_LENGTH, "발라하"
	fixed_string MON_NAME_LENGTH, "그렌델"
	fixed_string MON_NAME_LENGTH, "옥토퍼스"
	fixed_string MON_NAME_LENGTH, "뷔브르"
	fixed_string MON_NAME_LENGTH, "라마슈투"
	fixed_string MON_NAME_LENGTH, "쿠사릭쿠"
	fixed_string MON_NAME_LENGTH, "무슈후슈"
	fixed_string MON_NAME_LENGTH, "니드호그"
	fixed_string MON_NAME_LENGTH, "몰볼"
	fixed_string MON_NAME_LENGTH, "몰볼 그레이트"
	fixed_string MON_NAME_LENGTH, "오거"
	fixed_string MON_NAME_LENGTH, "아수라"
	fixed_string MON_NAME_LENGTH, "피라냐"
	fixed_string MON_NAME_LENGTH, "피라냐"
	fixed_string MON_NAME_LENGTH, "피라냐"
	fixed_string MON_NAME_LENGTH, "스플래셔"
	fixed_string MON_NAME_LENGTH, "스플래셔"
	fixed_string MON_NAME_LENGTH, "스플래셔"
	fixed_string MON_NAME_LENGTH, "베파르"
	fixed_string MON_NAME_LENGTH, "베파르"
	fixed_string MON_NAME_LENGTH, "베파르"
	fixed_string MON_NAME_LENGTH, "옐로 엘리멘트"
	fixed_string MON_NAME_LENGTH, "화이트 엘리멘트"
	fixed_string MON_NAME_LENGTH, "레드 엘리멘트"
	fixed_string MON_NAME_LENGTH, "골드 엘리멘트"
	fixed_string MON_NAME_LENGTH, "블루 엘리멘트"
	fixed_string MON_NAME_LENGTH, "다크 엘리멘트"
	fixed_string MON_NAME_LENGTH, "블랙 엘리멘트"
	fixed_string MON_NAME_LENGTH, "에페즈"
	fixed_string MON_NAME_LENGTH, "베히모스"
	fixed_string MON_NAME_LENGTH, "킹 베히모스"
	fixed_string MON_NAME_LENGTH, "키마이라"
	fixed_string MON_NAME_LENGTH, "키마이라 브레인"
	fixed_string MON_NAME_LENGTH, "쿠알"
	fixed_string MON_NAME_LENGTH, "마스터 쿠알"
	fixed_string MON_NAME_LENGTH, "오토 가더"
	fixed_string MON_NAME_LENGTH, "오토 스카우터"
	fixed_string MON_NAME_LENGTH, "오토 스카우터"
	fixed_string MON_NAME_LENGTH, "오토 커맨더"
	fixed_string MON_NAME_LENGTH, "데빌 모놀리스"
	fixed_string MON_NAME_LENGTH, "오토 거너"
	fixed_string MON_NAME_LENGTH, "오토 헌터"
	fixed_string MON_NAME_LENGTH, "오토 아머"
	fixed_string MON_NAME_LENGTH, "알테마 웨폰"
	fixed_string MON_NAME_LENGTH, "오메가 웨폰"
	fixed_string MON_NAME_LENGTH, "트로스"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 그노우』"
	fixed_string MON_NAME_LENGTH, "그노우의 촉수"
	fixed_string MON_NAME_LENGTH, "쵸코보 이터"
	fixed_string MON_NAME_LENGTH, "네슬러그"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "지오스게이노"
	fixed_string MON_NAME_LENGTH, "알베드 슈터"
	fixed_string MON_NAME_LENGTH, "알베드 캡처"
	fixed_string MON_NAME_LENGTH, "????"
	fixed_string MON_NAME_LENGTH, "『신』"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 에큐』"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 기이』"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "에프레이에"
	fixed_string MON_NAME_LENGTH, "에프레이에=알타나"
	fixed_string MON_NAME_LENGTH, "스피어 매니저"
	fixed_string MON_NAME_LENGTH, "알베드 거너"
	fixed_string MON_NAME_LENGTH, "알베드 실러"
	fixed_string MON_NAME_LENGTH, "Seymour"
	fixed_string MON_NAME_LENGTH, "아니마"
	fixed_string MON_NAME_LENGTH, "Seymour" ; 필드 미사용: 원본 "Seymour:{2c}"
	fixed_string MON_NAME_LENGTH, "환광이체"
	fixed_string MON_NAME_LENGTH, "성지의 가디언"
	fixed_string MON_NAME_LENGTH, "마천의 가디언"
	fixed_string MON_NAME_LENGTH, "유우나레스카"
	fixed_string MON_NAME_LENGTH, "Seymour" ; 필드 미사용: 원본 "Seymour:{2e}"
	fixed_string MON_NAME_LENGTH, "브라스카의 궁극 소환수"
	fixed_string MON_NAME_LENGTH, "크레인"
	fixed_string MON_NAME_LENGTH, "비란=론조"
	fixed_string MON_NAME_LENGTH, "엔케=론조"
	fixed_string MON_NAME_LENGTH, "『신의 왼팔』"
	fixed_string MON_NAME_LENGTH, "『신의 오른팔』"
	fixed_string MON_NAME_LENGTH, "『신』"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 구나이』"
	fixed_string MON_NAME_LENGTH, "『신』"
	fixed_string MON_NAME_LENGTH, "구아드·가드"
	fixed_string MON_NAME_LENGTH, "Seymour" ; 필드 미사용: 원본 "Seymour:{2d}"
	fixed_string MON_NAME_LENGTH, "환광기기"
	fixed_string MON_NAME_LENGTH, "키마리 무기"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "서클"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "시드"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "뷔브르"
	fixed_string MON_NAME_LENGTH, "알베드 포터"
	fixed_string MON_NAME_LENGTH, "떠돌이 오츄"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "사하긴"
	fixed_string MON_NAME_LENGTH, "사하긴 치프"
	fixed_string MON_NAME_LENGTH, "가루다"
	fixed_string MON_NAME_LENGTH, "클릭"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 엠즈』"
	fixed_string MON_NAME_LENGTH, "머리"
	fixed_string MON_NAME_LENGTH, "팔"
	fixed_string MON_NAME_LENGTH, "게이트 자물쇠"
	fixed_string MON_NAME_LENGTH, "발파레"
	fixed_string MON_NAME_LENGTH, "이프리트"
	fixed_string MON_NAME_LENGTH, "익시온"
	fixed_string MON_NAME_LENGTH, "시바"
	fixed_string MON_NAME_LENGTH, "바하무트"
	fixed_string MON_NAME_LENGTH, "아니마"
	fixed_string MON_NAME_LENGTH, "요짐보"
	fixed_string MON_NAME_LENGTH, "탱크로리"
	fixed_string MON_NAME_LENGTH, "게이트 자물쇠"
	fixed_string MON_NAME_LENGTH, "몬스터 172"
	fixed_string MON_NAME_LENGTH, "유=파고다"
	fixed_string MON_NAME_LENGTH, "유=파고다"
	fixed_string MON_NAME_LENGTH, "촉수"
	fixed_string MON_NAME_LENGTH, "유=에본"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "마그"
	fixed_string MON_NAME_LENGTH, "도그"
	fixed_string MON_NAME_LENGTH, "라그"
	fixed_string MON_NAME_LENGTH, "철거인"
	fixed_string MON_NAME_LENGTH, "울프라마이터"
	fixed_string MON_NAME_LENGTH, "울프라마이터"
	fixed_string MON_NAME_LENGTH, "울프라마이터"
	fixed_string MON_NAME_LENGTH, "바질리스크"
	fixed_string MON_NAME_LENGTH, "헤지 바이퍼"
	fixed_string MON_NAME_LENGTH, "아다만타이마이"
	fixed_string MON_NAME_LENGTH, "바르나"
	fixed_string MON_NAME_LENGTH, "오츄"
	fixed_string MON_NAME_LENGTH, "만드라고라"
	fixed_string MON_NAME_LENGTH, "암룡 99형"
	fixed_string MON_NAME_LENGTH, "암룡 97형"
	fixed_string MON_NAME_LENGTH, "봄"
	fixed_string MON_NAME_LENGTH, "그레네이드"
	fixed_string MON_NAME_LENGTH, "철기 63형"
	fixed_string MON_NAME_LENGTH, "철기 11형"
	fixed_string MON_NAME_LENGTH, "승병"
	fixed_string MON_NAME_LENGTH, "영당 승병"
	fixed_string MON_NAME_LENGTH, "승병"
	fixed_string MON_NAME_LENGTH, "영당 승병"
	fixed_string MON_NAME_LENGTH, "코요코요"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "사보텐더?"
	fixed_string MON_NAME_LENGTH, "사보텐더"
	fixed_string MON_NAME_LENGTH, "랄바"
	fixed_string MON_NAME_LENGTH, "발바토스"
	fixed_string MON_NAME_LENGTH, "???"
	fixed_string MON_NAME_LENGTH, "웬디고"
	fixed_string MON_NAME_LENGTH, "구아드·가드"
	fixed_string MON_NAME_LENGTH, "풍고온고"
	fixed_string MON_NAME_LENGTH, "손"
	fixed_string MON_NAME_LENGTH, "안테산산"
	fixed_string MON_NAME_LENGTH, "크시포스"
	fixed_string MON_NAME_LENGTH, "퓨로보로스"
	fixed_string MON_NAME_LENGTH, "스피릿"
	fixed_string MON_NAME_LENGTH, "레이스"
	fixed_string MON_NAME_LENGTH, "샌드 발삼"
	fixed_string MON_NAME_LENGTH, "구아드·가드"
	fixed_string MON_NAME_LENGTH, "トンベリ"
	fixed_string MON_NAME_LENGTH, "マスタートンベリ"
	fixed_string MON_NAME_LENGTH, "イービルアイ"
	fixed_string MON_NAME_LENGTH, "ボム"
	fixed_string MON_NAME_LENGTH, "キマイラ"
	fixed_string MON_NAME_LENGTH, "デュアルホーン"
	fixed_string MON_NAME_LENGTH, "護法戦機"
	fixed_string MON_NAME_LENGTH, "ガルダ"
	fixed_string MON_NAME_LENGTH, "ディンゴ"
	fixed_string MON_NAME_LENGTH, "ウォータプリン"
	fixed_string MON_NAME_LENGTH, "コンドル"
	fixed_string MON_NAME_LENGTH, "バルサム"
	fixed_string MON_NAME_LENGTH, "ラルド"
	fixed_string MON_NAME_LENGTH, "バニップ"
	fixed_string MON_NAME_LENGTH, "???"
	fixed_string MON_NAME_LENGTH, "ズー"
	fixed_string MON_NAME_LENGTH, "ザウラス"
	fixed_string MON_NAME_LENGTH, "ハァルマ"
	fixed_string MON_NAME_LENGTH, "アクアプリン"
	fixed_string MON_NAME_LENGTH, "デスフロート"
	fixed_string MON_NAME_LENGTH, "メイズラルヴァ"
	fixed_string MON_NAME_LENGTH, "メチーエ"
	fixed_string MON_NAME_LENGTH, "ケイブシュメルケ"
	fixed_string MON_NAME_LENGTH, "スワンプマフート"
	fixed_string MON_NAME_LENGTH, "バットアイ"
	fixed_string MON_NAME_LENGTH, "イサール"
	fixed_string MON_NAME_LENGTH, "マイラ"
	fixed_string MON_NAME_LENGTH, "ベルゲミーネ"
	fixed_string MON_NAME_LENGTH, "ミミック"
	fixed_string MON_NAME_LENGTH, "ミミック"
	fixed_string MON_NAME_LENGTH, "ミミック"
	fixed_string MON_NAME_LENGTH, "ヴァルファーレ"
	fixed_string MON_NAME_LENGTH, "ダミー"
	fixed_string MON_NAME_LENGTH, "ミミック"
	fixed_string MON_NAME_LENGTH, "ミミックパーツ"
	fixed_string MON_NAME_LENGTH, "ヴァルファーレ"
	fixed_string MON_NAME_LENGTH, "イフリート"
	fixed_string MON_NAME_LENGTH, "ミミックパーツ"
	fixed_string MON_NAME_LENGTH, "ミミックパーツ"
	fixed_string MON_NAME_LENGTH, "ミミックパーツ"
	fixed_string MON_NAME_LENGTH, "ライフル"
	fixed_string MON_NAME_LENGTH, "ファイアライフル"
	fixed_string MON_NAME_LENGTH, "アニマ"
	fixed_string MON_NAME_LENGTH, "こまいぬ"
	fixed_string MON_NAME_LENGTH, "アニマ"
	fixed_string MON_NAME_LENGTH, "アニマ"
	fixed_string MON_NAME_LENGTH, "かたな"
	fixed_string MON_NAME_LENGTH, "こづか"
	fixed_string MON_NAME_LENGTH, "しゅりけん"
	fixed_string MON_NAME_LENGTH, "あたま"
	fixed_string MON_NAME_LENGTH, "うで"
	fixed_string MON_NAME_LENGTH, "にしださんよやくずみ"
	fixed_string MON_NAME_LENGTH, "ツルギ"
	fixed_string MON_NAME_LENGTH, "すべてを超えし者"
	fixed_string MON_NAME_LENGTH, "カタストロフィ"
	fixed_string MON_NAME_LENGTH, "なし"
	fixed_string MON_NAME_LENGTH, "アースイーター"
	fixed_string MON_NAME_LENGTH, "アルテマバスター"
	fixed_string MON_NAME_LENGTH, "ヒュージスフィア"
	fixed_string MON_NAME_LENGTH, "ブラキオレイドス"
	fixed_string MON_NAME_LENGTH, "神龍"
	fixed_string MON_NAME_LENGTH, "イフリート"
	fixed_string MON_NAME_LENGTH, "イクシオン"
	fixed_string MON_NAME_LENGTH, "シヴァ"
	fixed_string MON_NAME_LENGTH, "バハムート"
	fixed_string MON_NAME_LENGTH, "ようじんぼう"
	fixed_string MON_NAME_LENGTH, "ドグ"
	fixed_string MON_NAME_LENGTH, "マグ"
	fixed_string MON_NAME_LENGTH, "ラグ"
	fixed_string MON_NAME_LENGTH, "タンケット"
	fixed_string MON_NAME_LENGTH, "ウィーザルシャ"
	fixed_string MON_NAME_LENGTH, "フェンリル"
	fixed_string MON_NAME_LENGTH, "ジャンボプリン"
	fixed_string MON_NAME_LENGTH, "オルニトレステス"
	fixed_string MON_NAME_LENGTH, "プテリクス"
	fixed_string MON_NAME_LENGTH, "ホーネット"
	fixed_string MON_NAME_LENGTH, "一つ目"
	fixed_string MON_NAME_LENGTH, "ストラトエイビス"
	fixed_string MON_NAME_LENGTH, "アビスウォーム"
	fixed_string MON_NAME_LENGTH, "ジャガーノート"
	fixed_string MON_NAME_LENGTH, "ファヴニル"
	fixed_string MON_NAME_LENGTH, "モルボルワースト"
	fixed_string MON_NAME_LENGTH, "闘鬼"
	fixed_string MON_NAME_LENGTH, "エレメンタル·ネガ"
	fixed_string MON_NAME_LENGTH, "カトブレパス"
	fixed_string MON_NAME_LENGTH, "キマイラガイスト"
	fixed_string MON_NAME_LENGTH, "クァールレギナ"
	fixed_string MON_NAME_LENGTH, "アイアンクラッド"
	fixed_string MON_NAME_LENGTH, "ヨルムンガンド"
	fixed_string MON_NAME_LENGTH, "アバドン"
	fixed_string MON_NAME_LENGTH, "ボムキング"
	fixed_string MON_NAME_LENGTH, "サポテンダー"
	fixed_string MON_NAME_LENGTH, "ヴォーバン"
	fixed_string MON_NAME_LENGTH, "ネムリダケ"
	fixed_string MON_NAME_LENGTH, "ドン·トンベリ"
	fixed_string MON_NAME_LENGTH, "エスパーダ"
	fixed_string MON_NAME_LENGTH, "ボム"
	fixed_string MON_NAME_LENGTH, "デュアルホーン"
	fixed_string MON_NAME_LENGTH, "ヴァルチャー"
	fixed_string MON_NAME_LENGTH, "バジリスク"
	fixed_string MON_NAME_LENGTH, "オチュー"
	fixed_string MON_NAME_LENGTH, "ラルヴァ"
	fixed_string MON_NAME_LENGTH, "鉄巨人"
	fixed_string MON_NAME_LENGTH, "キマイラ"
	fixed_string MON_NAME_LENGTH, "몬스터 84"
	fixed_string MON_NAME_LENGTH, "サボテンダー?"
	fixed_string MON_NAME_LENGTH, "ズー"
	fixed_string MON_NAME_LENGTH, "サンドウォーム"
	fixed_string MON_NAME_LENGTH, "ゴースト"
	fixed_string MON_NAME_LENGTH, "モルボル"
	fixed_string MON_NAME_LENGTH, "アシュラ"
	fixed_string MON_NAME_LENGTH, "헤레틱·발파레"
	fixed_string MON_NAME_LENGTH, "헤레틱·이프리트"
	fixed_string MON_NAME_LENGTH, "헤레틱·익시온"
	fixed_string MON_NAME_LENGTH, "헤레틱·시바"
	fixed_string MON_NAME_LENGTH, "헤레틱·바하무트"
	fixed_string MON_NAME_LENGTH, "헤레틱·아니마"
	fixed_string MON_NAME_LENGTH, "헤레틱·요짐보"
	fixed_string MON_NAME_LENGTH, "헤레틱·마그"
	fixed_string MON_NAME_LENGTH, "헤레틱·도그"
	fixed_string MON_NAME_LENGTH, "헤레틱·라그"
	fixed_string MON_NAME_LENGTH, "데어·리히터"
	fixed_string MON_NAME_LENGTH, "오른팔"
	fixed_string MON_NAME_LENGTH, "왼팔"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
