.align 4
monster_names:
	fixed_string MON_NAME_LENGTH, "몬스터 0"
	fixed_string MON_NAME_LENGTH, "랄도"
	fixed_string MON_NAME_LENGTH, "버니프"
	fixed_string MON_NAME_LENGTH, "무루프슈"
	fixed_string MON_NAME_LENGTH, "마프데트"
	fixed_string MON_NAME_LENGTH, "슈레드"
	fixed_string MON_NAME_LENGTH, "간다레와"
	fixed_string MON_NAME_LENGTH, "에어로지"
	fixed_string MON_NAME_LENGTH, "가르키마세라"
	fixed_string MON_NAME_LENGTH, "딩고"
	fixed_string MON_NAME_LENGTH, "미헨 팡"
	fixed_string MON_NAME_LENGTH, "가름"
	fixed_string MON_NAME_LENGTH, "스노우 울프"
	fixed_string MON_NAME_LENGTH, "샌드 울프"
	fixed_string MON_NAME_LENGTH, "스콜"
	fixed_string MON_NAME_LENGTH, "밴더스내치"
	fixed_string MON_NAME_LENGTH, "워터 푸딩"
	fixed_string MON_NAME_LENGTH, "선더 푸딩"
	fixed_string MON_NAME_LENGTH, "스노우 푸딩"
	fixed_string MON_NAME_LENGTH, "아이스 푸딩"
	fixed_string MON_NAME_LENGTH, "플레임 푸딩"
	fixed_string MON_NAME_LENGTH, "다크 푸딩"
	fixed_string MON_NAME_LENGTH, "디노닉스"
	fixed_string MON_NAME_LENGTH, "이피리아"
	fixed_string MON_NAME_LENGTH, "랩터"
	fixed_string MON_NAME_LENGTH, "멜뤼진"
	fixed_string MON_NAME_LENGTH, "슈메르케"
	fixed_string MON_NAME_LENGTH, "요위"
	fixed_string MON_NAME_LENGTH, "콘도르"
	fixed_string MON_NAME_LENGTH, "시무르그"
	fixed_string MON_NAME_LENGTH, "알키오네"
	fixed_string MON_NAME_LENGTH, "킬러 비"
	fixed_string MON_NAME_LENGTH, "바이트 버그"
	fixed_string MON_NAME_LENGTH, "와스프"
	fixed_string MON_NAME_LENGTH, "네비로스"
	fixed_string MON_NAME_LENGTH, "플로트 아이"
	fixed_string MON_NAME_LENGTH, "부에르"
	fixed_string MON_NAME_LENGTH, "이블 아이"
	fixed_string MON_NAME_LENGTH, "아리만"
	fixed_string MON_NAME_LENGTH, "발삼"
	fixed_string MON_NAME_LENGTH, "그랫"
	fixed_string MON_NAME_LENGTH, "사하긴"
	fixed_string MON_NAME_LENGTH, "사하긴"
	fixed_string MON_NAME_LENGTH, "사하긴"
	fixed_string MON_NAME_LENGTH, "가루다"
	fixed_string MON_NAME_LENGTH, "즈"
	fixed_string MON_NAME_LENGTH, "샌드 웜"
	fixed_string MON_NAME_LENGTH, "랜드 웜"
	fixed_string MON_NAME_LENGTH, "호법기사"
	fixed_string MON_NAME_LENGTH, "영식 호법기사"
	fixed_string MON_NAME_LENGTH, "고스트"
	fixed_string MON_NAME_LENGTH, "플레기아스"
	fixed_string MON_NAME_LENGTH, "아케오로스"
	fixed_string MON_NAME_LENGTH, "레모라"
	fixed_string MON_NAME_LENGTH, "레이징 스파이크"
	fixed_string MON_NAME_LENGTH, "듀얼 혼"
	fixed_string MON_NAME_LENGTH, "발라하"
	fixed_string MON_NAME_LENGTH, "그렌델"
	fixed_string MON_NAME_LENGTH, "옥토퍼스"
	fixed_string MON_NAME_LENGTH, "뷔브르"
	fixed_string MON_NAME_LENGTH, "라마슈투"
	fixed_string MON_NAME_LENGTH, "쿠사릭쿠"
	fixed_string MON_NAME_LENGTH, "무슈후슈"
	fixed_string MON_NAME_LENGTH, "니드호그"
	fixed_string MON_NAME_LENGTH, "몰볼"
	fixed_string MON_NAME_LENGTH, "몰볼 그레이트"
	fixed_string MON_NAME_LENGTH, "오거"
	fixed_string MON_NAME_LENGTH, "아수라"
	fixed_string MON_NAME_LENGTH, "피라냐"
	fixed_string MON_NAME_LENGTH, "피라냐"
	fixed_string MON_NAME_LENGTH, "피라냐"
	fixed_string MON_NAME_LENGTH, "스플래셔"
	fixed_string MON_NAME_LENGTH, "스플래셔"
	fixed_string MON_NAME_LENGTH, "스플래셔"
	fixed_string MON_NAME_LENGTH, "베파르"
	fixed_string MON_NAME_LENGTH, "베파르"
	fixed_string MON_NAME_LENGTH, "베파르"
	fixed_string MON_NAME_LENGTH, "옐로 엘리멘트"
	fixed_string MON_NAME_LENGTH, "화이트 엘리멘트"
	fixed_string MON_NAME_LENGTH, "레드 엘리멘트"
	fixed_string MON_NAME_LENGTH, "골드 엘리멘트"
	fixed_string MON_NAME_LENGTH, "블루 엘리멘트"
	fixed_string MON_NAME_LENGTH, "다크 엘리멘트"
	fixed_string MON_NAME_LENGTH, "블랙 엘리멘트"
	fixed_string MON_NAME_LENGTH, "에페즈"
	fixed_string MON_NAME_LENGTH, "베히모스"
	fixed_string MON_NAME_LENGTH, "킹 베히모스"
	fixed_string MON_NAME_LENGTH, "키마이라"
	fixed_string MON_NAME_LENGTH, "키마이라 브레인"
	fixed_string MON_NAME_LENGTH, "쿠알"
	fixed_string MON_NAME_LENGTH, "마스터 쿠알"
	fixed_string MON_NAME_LENGTH, "오토 가더"
	fixed_string MON_NAME_LENGTH, "오토 스카우터"
	fixed_string MON_NAME_LENGTH, "오토 스카우터"
	fixed_string MON_NAME_LENGTH, "오토 커맨더"
	fixed_string MON_NAME_LENGTH, "데빌 모놀리스"
	fixed_string MON_NAME_LENGTH, "오토 거너"
	fixed_string MON_NAME_LENGTH, "오토 헌터"
	fixed_string MON_NAME_LENGTH, "오토 아머"
	fixed_string MON_NAME_LENGTH, "알테마 웨폰"
	fixed_string MON_NAME_LENGTH, "오메가 웨폰"
	fixed_string MON_NAME_LENGTH, "트로스"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 그노우』"
	fixed_string MON_NAME_LENGTH, "그노우의 촉수"
	fixed_string MON_NAME_LENGTH, "쵸코보 이터"
	fixed_string MON_NAME_LENGTH, "네슬러그"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "지오스게이노"
	fixed_string MON_NAME_LENGTH, "알베드 슈터"
	fixed_string MON_NAME_LENGTH, "알베드 캡처"
	fixed_string MON_NAME_LENGTH, "????"
	fixed_string MON_NAME_LENGTH, "『신』"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 에큐』"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 기이』"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "에프레이에"
	fixed_string MON_NAME_LENGTH, "에프레이에=알타나"
	fixed_string MON_NAME_LENGTH, "스피어 매니저"
	fixed_string MON_NAME_LENGTH, "알베드 거너"
	fixed_string MON_NAME_LENGTH, "알베드 실러"
	fixed_string MON_NAME_LENGTH, "Seymour"
	fixed_string MON_NAME_LENGTH, "아니마"
	fixed_string MON_NAME_LENGTH, "Seymour" ; 필드 미사용: 원본 "Seymour:{2c}"
	fixed_string MON_NAME_LENGTH, "환광이체"
	fixed_string MON_NAME_LENGTH, "성지의 가디언"
	fixed_string MON_NAME_LENGTH, "마천의 가디언"
	fixed_string MON_NAME_LENGTH, "유우나레스카"
	fixed_string MON_NAME_LENGTH, "Seymour" ; 필드 미사용: 원본 "Seymour:{2e}"
	fixed_string MON_NAME_LENGTH, "브라스카의 궁극 소환수"
	fixed_string MON_NAME_LENGTH, "크레인"
	fixed_string MON_NAME_LENGTH, "비란=론조"
	fixed_string MON_NAME_LENGTH, "엔케=론조"
	fixed_string MON_NAME_LENGTH, "『신의 왼팔』"
	fixed_string MON_NAME_LENGTH, "『신의 오른팔』"
	fixed_string MON_NAME_LENGTH, "『신』"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 구나이』"
	fixed_string MON_NAME_LENGTH, "『신』"
	fixed_string MON_NAME_LENGTH, "구아드·가드"
	fixed_string MON_NAME_LENGTH, "Seymour" ; 필드 미사용: 원본 "Seymour:{2d}"
	fixed_string MON_NAME_LENGTH, "환광기기"
	fixed_string MON_NAME_LENGTH, "키마리 무기"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "서클"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "비늘 파펀"
	fixed_string MON_NAME_LENGTH, "시드"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "뷔브르"
	fixed_string MON_NAME_LENGTH, "알베드 포터"
	fixed_string MON_NAME_LENGTH, "떠돌이 오츄"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "사하긴"
	fixed_string MON_NAME_LENGTH, "사하긴 치프"
	fixed_string MON_NAME_LENGTH, "가루다"
	fixed_string MON_NAME_LENGTH, "클릭"
	fixed_string MON_NAME_LENGTH, "『신의 비늘: 엠즈』"
	fixed_string MON_NAME_LENGTH, "머리"
	fixed_string MON_NAME_LENGTH, "팔"
	fixed_string MON_NAME_LENGTH, "게이트 자물쇠"
	fixed_string MON_NAME_LENGTH, "발파레"
	fixed_string MON_NAME_LENGTH, "이프리트"
	fixed_string MON_NAME_LENGTH, "익시온"
	fixed_string MON_NAME_LENGTH, "시바"
	fixed_string MON_NAME_LENGTH, "바하무트"
	fixed_string MON_NAME_LENGTH, "아니마"
	fixed_string MON_NAME_LENGTH, "요짐보"
	fixed_string MON_NAME_LENGTH, "탱크로리"
	fixed_string MON_NAME_LENGTH, "게이트 자물쇠"
	fixed_string MON_NAME_LENGTH, "몬스터 172"
	fixed_string MON_NAME_LENGTH, "유=파고다"
	fixed_string MON_NAME_LENGTH, "유=파고다"
	fixed_string MON_NAME_LENGTH, "촉수"
	fixed_string MON_NAME_LENGTH, "유=에본"
	fixed_string MON_NAME_LENGTH, "환광천극"
	fixed_string MON_NAME_LENGTH, "마그"
	fixed_string MON_NAME_LENGTH, "도그"
	fixed_string MON_NAME_LENGTH, "라그"
	fixed_string MON_NAME_LENGTH, "철거인"
	fixed_string MON_NAME_LENGTH, "울프라마이터"
	fixed_string MON_NAME_LENGTH, "울프라마이터"
	fixed_string MON_NAME_LENGTH, "울프라마이터"
	fixed_string MON_NAME_LENGTH, "바질리스크"
	fixed_string MON_NAME_LENGTH, "헤지 바이퍼"
	fixed_string MON_NAME_LENGTH, "아다만타이마이"
	fixed_string MON_NAME_LENGTH, "바르나"
	fixed_string MON_NAME_LENGTH, "오츄"
	fixed_string MON_NAME_LENGTH, "만드라고라"
	fixed_string MON_NAME_LENGTH, "암룡 99형"
	fixed_string MON_NAME_LENGTH, "암룡 97형"
	fixed_string MON_NAME_LENGTH, "봄"
	fixed_string MON_NAME_LENGTH, "그레네이드"
	fixed_string MON_NAME_LENGTH, "철기 63형"
	fixed_string MON_NAME_LENGTH, "철기 11형"
	fixed_string MON_NAME_LENGTH, "승병"
	fixed_string MON_NAME_LENGTH, "영당 승병"
	fixed_string MON_NAME_LENGTH, "승병"
	fixed_string MON_NAME_LENGTH, "영당 승병"
	fixed_string MON_NAME_LENGTH, "코요코요"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "매직 포트"
	fixed_string MON_NAME_LENGTH, "사보텐더?"
	fixed_string MON_NAME_LENGTH, "사보텐더"
	fixed_string MON_NAME_LENGTH, "랄바"
	fixed_string MON_NAME_LENGTH, "발바토스"
	fixed_string MON_NAME_LENGTH, "???"
	fixed_string MON_NAME_LENGTH, "웬디고"
	fixed_string MON_NAME_LENGTH, "구아드·가드"
	fixed_string MON_NAME_LENGTH, "풍고온고"
	fixed_string MON_NAME_LENGTH, "손"
	fixed_string MON_NAME_LENGTH, "안테산산"
	fixed_string MON_NAME_LENGTH, "크시포스"
	fixed_string MON_NAME_LENGTH, "퓨로보로스"
	fixed_string MON_NAME_LENGTH, "스피릿"
	fixed_string MON_NAME_LENGTH, "레이스"
	fixed_string MON_NAME_LENGTH, "샌드 발삼"
	fixed_string MON_NAME_LENGTH, "구아드·가드"
	fixed_string MON_NAME_LENGTH, "톤베리"
	fixed_string MON_NAME_LENGTH, "마스터 톤베리"
	fixed_string MON_NAME_LENGTH, "이블 아이"
	fixed_string MON_NAME_LENGTH, "봄"
	fixed_string MON_NAME_LENGTH, "키마이라"
	fixed_string MON_NAME_LENGTH, "듀얼 혼"
	fixed_string MON_NAME_LENGTH, "호법 전기"
	fixed_string MON_NAME_LENGTH, "가루다"
	fixed_string MON_NAME_LENGTH, "딩고"
	fixed_string MON_NAME_LENGTH, "워터 푸딩"
	fixed_string MON_NAME_LENGTH, "콘도르"
	fixed_string MON_NAME_LENGTH, "발삼"
	fixed_string MON_NAME_LENGTH, "랄도"
	fixed_string MON_NAME_LENGTH, "버니프"
	fixed_string MON_NAME_LENGTH, "???"
	fixed_string MON_NAME_LENGTH, "즈"
	fixed_string MON_NAME_LENGTH, "자우러스"
	fixed_string MON_NAME_LENGTH, "할마"
	fixed_string MON_NAME_LENGTH, "아쿠아 푸딩"
	fixed_string MON_NAME_LENGTH, "데스 플로트"
	fixed_string MON_NAME_LENGTH, "메이즈 라바"
	fixed_string MON_NAME_LENGTH, "메치에"
	fixed_string MON_NAME_LENGTH, "케이브 슈메르케"
	fixed_string MON_NAME_LENGTH, "스왐프 마프데트"
	fixed_string MON_NAME_LENGTH, "뱃 아이"
	fixed_string MON_NAME_LENGTH, "이사르"
	fixed_string MON_NAME_LENGTH, "마일라"
	fixed_string MON_NAME_LENGTH, "베르게미네"
	fixed_string MON_NAME_LENGTH, "미믹"
	fixed_string MON_NAME_LENGTH, "미믹"
	fixed_string MON_NAME_LENGTH, "미믹"
	fixed_string MON_NAME_LENGTH, "발파레"
	fixed_string MON_NAME_LENGTH, "더미"
	fixed_string MON_NAME_LENGTH, "미믹"
	fixed_string MON_NAME_LENGTH, "미믹 파츠"
	fixed_string MON_NAME_LENGTH, "발파레"
	fixed_string MON_NAME_LENGTH, "이프리트"
	fixed_string MON_NAME_LENGTH, "미믹 파츠"
	fixed_string MON_NAME_LENGTH, "미믹 파츠"
	fixed_string MON_NAME_LENGTH, "미믹 파츠"
	fixed_string MON_NAME_LENGTH, "라이플"
	fixed_string MON_NAME_LENGTH, "파이어 라이플"
	fixed_string MON_NAME_LENGTH, "아니마"
	fixed_string MON_NAME_LENGTH, "코마이누"
	fixed_string MON_NAME_LENGTH, "아니마"
	fixed_string MON_NAME_LENGTH, "아니마"
	fixed_string MON_NAME_LENGTH, "검"
	fixed_string MON_NAME_LENGTH, "표창"
	fixed_string MON_NAME_LENGTH, "수리검"
	fixed_string MON_NAME_LENGTH, "머리"
	fixed_string MON_NAME_LENGTH, "팔"
	fixed_string MON_NAME_LENGTH, "니시다씨 예약됨"
	fixed_string MON_NAME_LENGTH, "대검"
	fixed_string MON_NAME_LENGTH, "모든 것을 초월한 자"
	fixed_string MON_NAME_LENGTH, "카타스트로피"
	fixed_string MON_NAME_LENGTH, "없음"
	fixed_string MON_NAME_LENGTH, "어스 이터"
	fixed_string MON_NAME_LENGTH, "알테마 버스터"
	fixed_string MON_NAME_LENGTH, "휴즈 스피어"
	fixed_string MON_NAME_LENGTH, "브라키오레이도스"
	fixed_string MON_NAME_LENGTH, "신룡"
	fixed_string MON_NAME_LENGTH, "이프리트"
	fixed_string MON_NAME_LENGTH, "익시온"
	fixed_string MON_NAME_LENGTH, "시바"
	fixed_string MON_NAME_LENGTH, "바하무트"
	fixed_string MON_NAME_LENGTH, "요짐보"
	fixed_string MON_NAME_LENGTH, "도그"
	fixed_string MON_NAME_LENGTH, "마그"
	fixed_string MON_NAME_LENGTH, "라그"
	fixed_string MON_NAME_LENGTH, "탱켓"
	fixed_string MON_NAME_LENGTH, "위자르샤"
	fixed_string MON_NAME_LENGTH, "펜리르"
	fixed_string MON_NAME_LENGTH, "점보 푸딩"
	fixed_string MON_NAME_LENGTH, "오르니톨레스테스"
	fixed_string MON_NAME_LENGTH, "프테리쿠스"
	fixed_string MON_NAME_LENGTH, "호넷"
	fixed_string MON_NAME_LENGTH, "외눈박이"
	fixed_string MON_NAME_LENGTH, "스트라토아비스"
	fixed_string MON_NAME_LENGTH, "아비스 웜"
	fixed_string MON_NAME_LENGTH, "저거너트"
	fixed_string MON_NAME_LENGTH, "파브니르"
	fixed_string MON_NAME_LENGTH, "몰볼 워스트"
	fixed_string MON_NAME_LENGTH, "투귀"
	fixed_string MON_NAME_LENGTH, "엘리멘탈·네거"
	fixed_string MON_NAME_LENGTH, "카토블레파스"
	fixed_string MON_NAME_LENGTH, "키마이라가이스트"
	fixed_string MON_NAME_LENGTH, "쿠알레지나"
	fixed_string MON_NAME_LENGTH, "아이언클래드"
	fixed_string MON_NAME_LENGTH, "요르문간드"
	fixed_string MON_NAME_LENGTH, "아바돈"
	fixed_string MON_NAME_LENGTH, "봄 킹"
	fixed_string MON_NAME_LENGTH, "사포텐더"
	fixed_string MON_NAME_LENGTH, "보반"
	fixed_string MON_NAME_LENGTH, "수면 버섯"
	fixed_string MON_NAME_LENGTH, "돈·톤베리"
	fixed_string MON_NAME_LENGTH, "에스파다"
	fixed_string MON_NAME_LENGTH, "봄"
	fixed_string MON_NAME_LENGTH, "듀얼 혼"
	fixed_string MON_NAME_LENGTH, "벌처"
	fixed_string MON_NAME_LENGTH, "바질리스크"
	fixed_string MON_NAME_LENGTH, "오츄"
	fixed_string MON_NAME_LENGTH, "라바"
	fixed_string MON_NAME_LENGTH, "철거인"
	fixed_string MON_NAME_LENGTH, "키마이라"
	fixed_string MON_NAME_LENGTH, "몬스터 84"
	fixed_string MON_NAME_LENGTH, "사보텐더?"
	fixed_string MON_NAME_LENGTH, "즈"
	fixed_string MON_NAME_LENGTH, "샌드 웜"
	fixed_string MON_NAME_LENGTH, "고스트"
	fixed_string MON_NAME_LENGTH, "몰볼"
	fixed_string MON_NAME_LENGTH, "아수라"
	fixed_string MON_NAME_LENGTH, "헤레틱·발파레"
	fixed_string MON_NAME_LENGTH, "헤레틱·이프리트"
	fixed_string MON_NAME_LENGTH, "헤레틱·익시온"
	fixed_string MON_NAME_LENGTH, "헤레틱·시바"
	fixed_string MON_NAME_LENGTH, "헤레틱·바하무트"
	fixed_string MON_NAME_LENGTH, "헤레틱·아니마"
	fixed_string MON_NAME_LENGTH, "헤레틱·요짐보"
	fixed_string MON_NAME_LENGTH, "헤레틱·마그"
	fixed_string MON_NAME_LENGTH, "헤레틱·도그"
	fixed_string MON_NAME_LENGTH, "헤레틱·라그"
	fixed_string MON_NAME_LENGTH, "데어·리히터"
	fixed_string MON_NAME_LENGTH, "오른팔"
	fixed_string MON_NAME_LENGTH, "왼팔"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
	fixed_string MON_NAME_LENGTH, "불명"
